<Root>
  <FileList>
    <File>$DocPath$\cliche\cli_init.sac</File>
    <File>$DocPath$\cliche\step1.sac</File>
    <File>$DocPath$\cliche\step2.sac</File>
    <File>$DocPath$\cliche\step3.sac</File>
    <File>$DocPath$\cliche\step4.sac</File>
    <File>$DocPath$\cliche\step5.sac</File>
    <File>$DocPath$\cliche\step6.sac</File>
    <File>$DocPath$\cliche\step7.sac</File>
  </FileList>
</Root>