<Root>
  <FileList>
    <File>$DocPath$\cliche\cli_init.sac</File>
    <File>$DocPath$\cliche\step1.sac</File>
    <File>$DocPath$\cliche\step2.sac</File>
    <File>$DocPath$\cliche\step4.sac</File>
    <File>$DocPath$\cliche\step5.sac</File>
    <File>$DocPath$\cliche\step6.sac</File>
    <File>$DocPath$\cliche\step7.sac</File>
    <File>$DocPath$\cliche\step8.sac</File>
    <File>$DocPath$\cliche\step9.sac</File>
    <File>$DocPath$\cliche\step10.sac</File>
    <File>$DocPath$\cliche\step11.sac</File>
    <File>$DocPath$\cliche\step12.sac</File>
    <File>$DocPath$\cliche\step13.sac</File>
    <File>$DocPath$\cliche\step14.sac</File>
    <File>$DocPath$\cliche\step15.sac</File>
    <File>$DocPath$\cliche\step16.sac</File>
    <File>$DocPath$\cliche\step17.sac</File>
    <File>$DocPath$\cliche\step18.sac</File>
    <File>$DocPath$\cliche\step19.sac</File>
    <File>$DocPath$\cliche\step20.sac</File>
    <File>$DocPath$\cliche\step21.sac</File>
    <File>$DocPath$\cliche\step22.sac</File>
    <File>$DocPath$\cliche\step23.sac</File>
  </FileList>
</Root>